baseURL = "https://zn83.github.io/Personal_Portfolio/"
languageCode = "fr-fr"
title = "Personal Portfolio"
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.profileMode]
  enabled = false

[params.assets]
  customCSS = ["css/custom.css"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/#about"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Articles"
    url = "/posts/"
    weight = 2