baseURL = "https://zn83.github.io/Personal_Portfolio/"
languageCode = "fr-fr"
title = "Mon Portfolio"
theme = "PaperMod"

[params.homeInfoParams]
  Title = "Bienvenue !"
  Content = "Voici mon portfolio."

[params.profileMode]
  enabled = true
  title = "Zian"
  subtitle = "Développeur, créatif, curieux."
  imageUrl = "images/Corporate_detouree_carree.png"
  imageTitle = "Ma photo"
  imageWidth = 120
  imageHeight = 120

[menu]
  [[menu.main]]
    identifier = "about"
    name = "À propos"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Articles"
    url = "/posts/"
    weight = 2