baseURL = "https://zn83.github.io/Personal_Portfolio/"
languageCode = "fr-fr"
title = "Mon Portfolio"
theme = "PaperMod"

[params]
  homeInfoParams = { Title = "Bienvenue !", Content = "Voici mon portfolio." }

[menu]
[[menu.main]]
  identifier = "about"
  name = "À propos"
  url = "/about/"