baseURL = "https://zn83.github.io/Personal_Portfolio/"
languageCode = "fr-fr"
title = "Personal Portfolio"
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  env = "production"
  defaultTheme = "dark"
  disableThemeToggle = true

[params.profileMode]
  enabled = false

[params.assets]
  customCSS = ["css/custom.css"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/#about"
    weight = 1

  [[menu.main]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/zian-cassassolles/"
    weight = 2
    pre = "<i class='fab fa-linkedin' style='margin-right: 4px;'></i>"
    params = { target = "_blank" }